### ISSUE TITLE
Out-Of-Order events exception in PerformanceTest

### ISSUE THREAD

**Issue by ismaelhamed** [Microsoft/TrillSamples#10]
When running the PerformanceTest with more than 5M `TotalInputEvents`, I always get:

```
Caching the input dataset into main memory...

Unhandled Exception: Microsoft.StreamProcessing.StreamProcessingException: Out-of-order event received during Cache() call
   at Microsoft.StreamProcessing.RxReplacements.SynchronousForEachWorker`1.DoIt(IObservable`1 observable, Action`1 action) in D:\a\1\s\Sources\Core\Microsoft.StreamProcessing\Utilities\RxReplacements.cs:line 40
   at Microsoft.StreamProcessing.Streamable.Cache[TKey,TPayload](IStreamable`2 stream, UInt64 limit, Boolean inferProperties, Boolean coalesceEndEdges) in D:\a\1\s\Sources\Core\Microsoft.StreamProcessing\CacheUtilities\StreamableIO.cs:line 89
   at PerformanceTest.Program.Main(String[] args)
```

**Comment by peterfreiling** [comment]
Thanks @ismaelhamed , this exposed a bug in Trill that has been fixed by https://github.com/Microsoft/Trill/pull/75. PR in TrillSamples that updates the Trill Nuget version with this fix - #11
